### PR TITLE
Introduction of the possibility to use triangle as a `point` to make … scatter plots

### PR DESCRIPTION
**Pull request by jposada202020**
Purpose of this PR is to add the feature to use the triangle shape in the adafruit_shapes library in the scatter plot.
To facilitate the usage equilateral triangles are used.
Please review. I have not tested this as I do not have the HW setup.

### CODE REVIEW

**Comment by jposada202020** [comment]
This was tested using Blinka displayio
image

and
```python
Adafruit CircuitPython 6.2.0-beta.3 on 2021-03-04; Seeeduino Wio Terminal with samd51p19
```
image

**Comment by jposada202020** [comment]
@romilly  This is ready for review. Thanks

**Comment by romilly** [comment]
Thanks - that's a useful extension.

Most of the code could go in the abstract plotter class. That would make it easier to add the same functionality to the Pimoroni Explorer code. I'll do the refactoring in the nest day or so.

**Comment by jposada202020** [comment]
No problem, I will add the functionalities in the abstract plotter class, I did not know it I could cause some short-circuit with the micropython code. I want to add the possibility also to use vertical text. So let me know, if the abstract class is the way to go.
Thanks for reviewing.

**Comment by romilly** [comment]
I'm trying to keep common code in the abstract class and implementations for each new capability in the concrete sub-classes. So the code that sets the corners of the triangle should be in the abstract class, and code to draw triangles should be in the displayio and explorer plotter classes.

I like the idea of supporting vertical text. I am not sure if that ability is in the Pimoroni Explorer Base API; we might need to add low-level vertical text code to the abstract class, and override it in the displayio code if that supports it directly. I'll take a look.

**Comment by jposada202020** [comment]
Perfect, understood. let me know if there anything else that you are exploring, I would like to contribute more

**Pull request merged**
